mappings:
  QuickCouponAdmin: Sunnysideup\EcommerceQuickCoupons\Cms\QuickCouponAdmin
  GridFieldCreateCouponFromInternalItemIDButton: Sunnysideup\EcommerceQuickCoupons\Forms\Gridfield\GridFieldCreateCouponFromInternalItemIDButton
  QuickCouponOption: Sunnysideup\EcommerceQuickCoupons\Model\QuickCouponOption
